name: nav_flex
description: "This package demonstrates a custom navigation system for Flutter applications" 
version: 0.0.1+1
repository: https://github.com/NgoTaiCo/nav_flex

environment:
  sdk: ^3.5.4 

dependencies:
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter:
  uses-material-design: true